server:
  port: 8787

spring:
  application:
    name: EMPLOYEE-MANAGEMENT
  cloud:
    config:
      uri: http://localhost:8888
      name: services.yml
      label: main
  config:
    import:
      - optional:file:.env[.properties]
      - configserver:http://localhost:8888

