spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:file:.env[.properties]


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG

---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring





