spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - AuthenticationFilter

        - id: kitchen-service
          uri: lb://KITCHEN-SERVICE
          predicates:
            - Path=/kitchen/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

  config:
    import: optional:file:.env[.properties]


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG

# JWT secret key
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000




