spring:
  application:
    name: API-GATEWAY

  config:
    import: optional:file:.env[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate.endpoint.web: DEBUG

---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/oauth2-springboot-realm

# Actuator endpoints
management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

# Resilience4j properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: customer service
        url: /aggregate/customer-service/v3/api-docs
      - name: inventory service
        url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /api-docs

employee:
  management:
    url: http://localhost:8787

invoicing:
  service:
    url: http://localhost:9090

customer:
  service:
    url: http://localhost:7878
