server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kisevu/config-repo
          force-pull: true
          skip-ssl-validation: true
          timeout: 10
          username: ${github-username}
          password: ${github-password}
          default-label: main
  config:
    import: optional:file:.env[.properties]



