server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user:
      name: configuser
      password: configPass$1234
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kisevu/config-repo
          force-pull: true
          skip-ssl-validation: true
          timeout: 10
          username: ${github-username}
          password: ${github-password}
  config:
    import: optional:file:.env[.properties]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



