services:
  postgres:
    container_name: postgres-sql-chat
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: oscaris-chat
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - oscaris-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak-chat
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - oscaris-network
    command:
      - "start-dev"


networks:
  oscaris-network:
    driver: bridge

volumes:
  postgres:
    driver: local